### ISSUE TITLE
About require and import load modules

### ISSUE THREAD

**Issue by stringang** [ssshooter/Front-End-EXP#1]
I think the following is wrong.

> import 同步，require异步（待补充）

Actually:

require is **sync**, import is **async**

**Comment by SSShooter** [comment]
That really makes me confused.Would you have a example to expalain it ?

**Comment by Yueyun** [comment]
> ECMAScript 6 modules must work independently of whether the engine loads modules synchronously (e.g. on servers) or asynchronously (e.g. in browsers). Its syntax is well suited for synchronous loading, asynchronous loading is enabled by its static structure: Because you can statically determine all imports, you can load them before evaluating the body of the module (in a manner reminiscent of AMD modules).

其实ES6 的import只是定义了规范，能支持同步/异步，最终实现是同步/异步，取决于loader api, webpack+babel都打包到一起了，就是同步的

**Comment by SSShooter** [comment]
单从打包来说是这样，但是 require 可以放到函数里异步引入
```js
function a(){
  var fs = require('fs')
}
```
import 则不可以，
从这点看可不可以说 import 同步，require异步呢？

**Comment by stringang** [comment]
### **import**
JavaScript performs static analysis on ES6 modules. The import statement needs to be at the top level, not in blocks and functions。

```
// invalid
if (true) {
  import test from './test';
}
```
### **require**
require is runtime loading.

### Reference

[require vs import](https://stackoverflow.com/a/31355283/5204695)

**Comment by SSShooter** [comment]
所以从引入这方面说 require 是不是异步呢？

**Comment by SSShooter** [comment]
而讨论 import 本身的异步同步似乎是没有意义的
![image](https://user-images.githubusercontent.com/13051472/43765304-3071c2d2-9a62-11e8-8b41-14bb26b49755.png)
